services:
  mapbender2_geometryprovider:
    class: OwsProxy3\CoreBundle\GeometryProvider\Mapbender2GeometryProvider
    arguments: [ "@service_container" ]

parameters:
    applications:
        mapbender_user:
            title: Mapbender User Demo Map Europe
            description: "Fullscreen style, Simple map showing WMS use."
            published: true
            template:  Mapbender\CoreBundle\Template\Fullscreen
            layersets:
                main:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: http://wms.wheregroup.com/cgi-bin/mapserv?map=/data/umn/mapbender_user/mapbender_user.map
                        layers:
                            - { name: Mapbender_User,    title : User, visible: true, legend: http://wms.wheregroup.com/cgi-bin/mapserv?map=/data/umn/mapbender_user/mapbender_user.map&REQUEST=GetLegendGraphic&VERSION=1.1.1&SERVICE=WMS&Layer=Mapbender_User&FORMAT=image/png }
                            - { name: Mapbender_Names,   title : Name, visible: true, queryable: true }
                        info_format: text/html
                        baselayer: false
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 85
                        legendgraphic: http://wms.wheregroup.com/cgi-bin/mapserv?map=/data/umn/mapbender_user/mapbender_user.map&REQUEST=GetLegendGraphic&VERSION=1.1.1&SERVICE=WMS
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender OSM
                        url: http://osm-demo.wheregroup.com/service
                        layers:
                            - { name: osm,    title : OSM-Demo WhereGroup,  visible: true }
                        info_format: text/html
                        baselayer: false
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 85                        
                overview:
                    osm_overview:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender OSM
                        url: http://osm-demo.wheregroup.com/service
                        layers:
                            - { name: osm,    title : OSM-Demo WhereGroup,  visible: true }
                        tiled: false
                        visible: true
                        baselayer: true
            elements:
                toolbar:
                    about:
                        title: About
                        tooltip: About
                        label: true
                        class: Mapbender\CoreBundle\Element\AboutDialog
                    print-button:
                        title: Drucken
                        tooltip: PDF Drucken
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        target: printclient
                        action: open
                    fi-button:
                        title: Information
                        class: Mapbender\CoreBundle\Element\Button
                        icon: featureinfo
                        label: true
                        target: featureinfo
                        action: activate
                        deactivate: deactivate
                    legend-button:
                        title: Legende
                        class: Mapbender\CoreBundle\Element\Button
                        target: legend
                        action: open
                    wmsloader-button:
                        title: WMS Laden
                        class: Mapbender\CoreBundle\Element\Button
                        target: wmsloader
                        action: open
                content:
                    map:
                        title: Main Map
                        class: Mapbender\CoreBundle\Element\Map
                        layerset: main
                        dpi: 72
                        srs: "EPSG:25832"
                        units: m 
                        extents:
                            start: [468936.0972297554253601,5734613.8816028153523803,514772.5749767934903502,5771039.8654772201552987]
                            max: [456123.496175453,5725783.96252051,523755.83,5782643.84]
                            #max: [456123.496175453,5725783.96252051,518127.873854555,5773860.80086785]
                        scales: [250000,125000,75000,50000,25000,10000,7500,5000]
                        maxResolution: 'auto'
                        imgPath: "bundles/mapbendercore/mapquery/lib/openlayers/img"
                        otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:4326"]
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        components: ["pan","history","zoom_box","zoom_max","zoom_slider"]
                        position: [15em, 3em]
                        stepsize: 50
                        stepbypixel: true
                        anchor: right-top
                        position: [200,40]
                        dragable: false          
                    legend:
                        class: Mapbender\CoreBundle\Element\Legend
                        target: map
                        title: Legende
                        elementType: dialog #dialog/blockelement
                        autoOpen: true
                        displayType: list #list/accordion
                        checkGraphic: false
                        hideEmptyLayers: true
                        noLegend: "Keine Legende vorhanden"
                        generateLegendGraphic: false
                        showSourceTitle: true
                        showLayerTitle: true
                        showGroupedTitle: true                   
                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        title: FeatureInfo
                        target: map
                        autoOpen: false
                        deactivateOnClose: true 
                    wmsloader:
                        title: Wms Laden
                        class: Mapbender\WmsBundle\Element\WmsLoader
                        target: map
                        autoOpen: true
                    printclient:
                        class: Mapbender\CoreBundle\Element\PrintClient
                        target: map
                        autoOpen: false
                        print_directly: true
                        templates:
                            a4portrait:
                                label: A4 Portrait
                                format: a4
                            a4landscape:
                                label: A4 Landscape
                                format: a4
                        scales: [500, 1000, 5000, 10000, 25000]
                        quality_levels: 
                            72: Entwurf
                            288: Dokument
                        rotatable: true
                        optional_fields: ~